{{- define "common.service" -}} # Define o template e seu nome
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }} # Quando o template for utilizado, o valor de serviceName será substituído/injetado pelo valor passado no arquivo values.yaml
spec:
  selector:
    app: {{ .Values.appLabel }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end -}} # Finaliza o template